version: "3.8"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 3248
      POSTGRES_DB: khmissa-shake
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prisma-studio:
    build:
      context: ./backend
      target: prisma-studio
    ports:
      - 5555:5555
    environment:
      DATABASE_URL: postgresql://root:3248@postgres:5432/khmissa-shake
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      target: base
    environment:
      DATABASE_URL: postgresql://root:3248@postgres:5432/khmissa-shake
      NODE_ENV: development
      PRISMA_STUDIO_URL: http://prisma-studio:5555
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - prisma-studio
    volumes:
      - ./backend:/app
      - /app/node_modules
      - prisma-data:/app/prisma
    command: pnpm run start:dev
volumes:
  postgres-data:
  prisma-data:
