version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3333
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: runner
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/khmissa
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=khmissa
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
